import { Cinema2ThreeAssetRegistry } from './Cinema2ThreeAssetRegistry'

export const CINEMA2_REFERENCE_TORUS_KNOT_ASSET_ID = 'cinema2-reference-torus-knot'

/**
 * Hand-authored asset manifest (the roadmap's #7 pipeline will generate this). Every record needs a license.
 * `cinema2-reference-torus-knot` is generated by code in this repository (a 24k-triangle torus knot with a dark glossy
 * PBR material), meshopt-compressed, and exists to exercise the Three.js module end to end.
 */
export const cinema2ThreeAssetRegistry = new Cinema2ThreeAssetRegistry()

cinema2ThreeAssetRegistry.register({
  id: CINEMA2_REFERENCE_TORUS_KNOT_ASSET_ID,
  url: '/cinema2/models/reference-torus-knot.glb',
  compression: 'meshopt',
  license: 'generated-in-house',
  triangleCount: 24000,
})
