import {
  CINEMA2_NATIVE_PRESET_SCHEMA_ID,
  CINEMA2_NATIVE_PRESET_SCHEMA_VERSION,
  cinema2NamespacedId,
  cinema2Ref,
  cinema2StableId,
  type Cinema2ChoreographyActionId,
  type Cinema2ChoreographyRuleId,
  type Cinema2LayerId,
  type Cinema2ModuleId,
  type Cinema2NativePresetManifest,
  type Cinema2ParameterId,
  type Cinema2PresetId,
  type Cinema2SceneNodeId,
} from '../contracts/Cinema2NativePresetManifest'
import {
  CINEMA2_HUMN_FRAGMENT_SOURCE,
  CINEMA2_HUMN_NATIVE_MODULE_TYPE_ID,
  CINEMA2_HUMN_NATIVE_MODULE_VERSION,
} from '../modules/Cinema2HumNNativeModule'
import { CINEMA2_QUALITY_MODE_PARAMETER } from '../parameters/Cinema2PerformanceParameters'

export const CINEMA2_HUMN_PRESET_ID = cinema2NamespacedId<Cinema2PresetId>('drmvyz.cinema2.hum-n')
export const CINEMA2_HUMN_MODULE_ID = cinema2StableId<Cinema2ModuleId>('hum-n-emergence')
export const CINEMA2_HUMN_ROOT_NODE_ID = cinema2StableId<Cinema2SceneNodeId>('hum-n-root')
export const CINEMA2_HUMN_MODULE_NODE_ID = cinema2StableId<Cinema2SceneNodeId>('hum-n-emergence-node')
export const CINEMA2_HUMN_LAYER_ID = cinema2StableId<Cinema2LayerId>('hum-n-emergence-layer')

export const CINEMA2_HUMN_LINE_PRESENCE_ID = cinema2StableId<Cinema2ParameterId>('hum-n-line-presence')
export const CINEMA2_HUMN_LINE_WEIGHT_ID = cinema2StableId<Cinema2ParameterId>('hum-n-line-weight')
export const CINEMA2_HUMN_FRAGMENTATION_ID = cinema2StableId<Cinema2ParameterId>('hum-n-fragmentation')
export const CINEMA2_HUMN_MESH_DETAIL_ID = cinema2StableId<Cinema2ParameterId>('hum-n-mesh-detail')
export const CINEMA2_HUMN_FACET_FILL_ID = cinema2StableId<Cinema2ParameterId>('hum-n-facet-fill')
export const CINEMA2_HUMN_FILL_STYLE_ID = cinema2StableId<Cinema2ParameterId>('hum-n-fill-style')
export const CINEMA2_HUMN_MASTER_INTENSITY_ID = cinema2StableId<Cinema2ParameterId>('hum-n-master-intensity')
export const CINEMA2_HUMN_BPM_SYNC_ID = cinema2StableId<Cinema2ParameterId>('hum-n-bpm-sync')
export const CINEMA2_HUMN_MOTION_AMOUNT_ID = cinema2StableId<Cinema2ParameterId>('hum-n-motion-amount')
export const CINEMA2_HUMN_MOTION_RATE_ID = cinema2StableId<Cinema2ParameterId>('hum-n-motion-rate')
export const CINEMA2_HUMN_FIGURE_SCALE_ID = cinema2StableId<Cinema2ParameterId>('hum-n-figure-scale')
export const CINEMA2_HUMN_GRID_PRESENCE_ID = cinema2StableId<Cinema2ParameterId>('hum-n-grid-presence')
export const CINEMA2_HUMN_BACKGROUND_ID = cinema2StableId<Cinema2ParameterId>('hum-n-background')
export const CINEMA2_HUMN_WIREFRAME_ID = cinema2StableId<Cinema2ParameterId>('hum-n-wireframe')
export const CINEMA2_HUMN_PATTERN_INK_ID = cinema2StableId<Cinema2ParameterId>('hum-n-pattern-ink')
export const CINEMA2_HUMN_SKIN_PRIMARY_ID = cinema2StableId<Cinema2ParameterId>('hum-n-skin-primary')
export const CINEMA2_HUMN_SKIN_SECONDARY_ID = cinema2StableId<Cinema2ParameterId>('hum-n-skin-secondary')
export const CINEMA2_HUMN_SKIN_ACCENT_ID = cinema2StableId<Cinema2ParameterId>('hum-n-skin-accent')
export const CINEMA2_HUMN_MASTER_REACTIVITY_ID = cinema2StableId<Cinema2ParameterId>('hum-n-master-reactivity')
export const CINEMA2_HUMN_COLOR_SHIFT_AMOUNT_ID = cinema2StableId<Cinema2ParameterId>('hum-n-color-shift-amount')
export const CINEMA2_HUMN_FLICKER_AMOUNT_ID = cinema2StableId<Cinema2ParameterId>('hum-n-flicker-amount')
export const CINEMA2_HUMN_FRAGMENT_JITTER_ID = cinema2StableId<Cinema2ParameterId>('hum-n-fragment-jitter')

const choreographyRuleId = (id: string) => cinema2StableId<Cinema2ChoreographyRuleId>(id)
const choreographyActionId = (id: string) => cinema2StableId<Cinema2ChoreographyActionId>(id)

const CINEMA2_HUMN_COMPOSITION_OUTPUT_PARAMETERS = Object.freeze([
  Object.freeze({
    id: CINEMA2_HUMN_MASTER_INTENSITY_ID,
    label: 'Master Intensity',
    description: 'Controls the final HUM:N figure and facet output strength without changing the technical stage or grid.',
    type: 'float' as const,
    defaultValue: 1,
    min: 0,
    max: 1,
    step: 0.01,
    section: 'Design',
    designParentGroup: 'master-controls' as const,
    order: 1,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_BPM_SYNC_ID,
    label: 'BPM Sync',
    description: 'Uses the shared Cinema 2.0 synced-motion clock for HUM:N native movement. This remains a hard user-owned authorization.',
    type: 'boolean' as const,
    defaultValue: true,
    section: 'Design',
    designParentGroup: 'master-controls' as const,
    order: 2,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_MASTER_REACTIVITY_ID,
    label: 'Master Reactivity',
    description: 'Global authorization multiplier for HUM:N continuous music modulation. At 0, all music-reactive behaviors collapse to user-authored base values.',
    type: 'float' as const,
    defaultValue: 0,
    min: 0,
    max: 1,
    step: 0.01,
    section: 'Design',
    designParentGroup: 'master-controls' as const,
    order: 3,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_FIGURE_SCALE_ID,
    label: 'Figure Scale',
    description: 'Uniformly scales the complete HUM:N figure around the approved composition anchor while preserving its proportions.',
    type: 'float' as const,
    defaultValue: 1,
    min: 0.7,
    max: 1.3,
    step: 0.01,
    section: 'Design',
    group: 'Composition',
    designParentGroup: 'design' as const,
    order: 1,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_GRID_PRESENCE_ID,
    label: 'Grid Presence',
    description: 'Controls only the restrained technical background grid while leaving the near-black stage intact.',
    type: 'float' as const,
    defaultValue: 1,
    min: 0,
    max: 1,
    step: 0.01,
    section: 'Design',
    group: 'Stage',
    designParentGroup: 'design' as const,
    order: 2,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
])

const CINEMA2_HUMN_PALETTE_PARAMETERS = Object.freeze([
  Object.freeze({
    id: CINEMA2_HUMN_BACKGROUND_ID,
    label: 'Background',
    description: 'Sets only the HUM:N stage/background surface color without recoloring the grid, figure line art, or facet pattern ink.',
    type: 'color' as const,
    defaultValue: Object.freeze([0, 0, 0, 1]),
    section: 'Design',
    group: 'Stage Colors',
    designParentGroup: 'palette' as const,
    order: 1,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_WIREFRAME_ID,
    label: 'Wireframe',
    description: 'Sets the primary HUM:N topology line color while preserving authored line hierarchy and leaving Pattern Ink independent.',
    type: 'color' as const,
    defaultValue: Object.freeze([245 / 255, 247 / 255, 250 / 255, 1]),
    section: 'Design',
    group: 'Figure Colors',
    designParentGroup: 'palette' as const,
    order: 2,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_PATTERN_INK_ID,
    label: 'Pattern Ink',
    description: 'Sets the bright ink used by Stripe and Mixed skin-facet graphics without recoloring the stage or topology lines.',
    type: 'color' as const,
    defaultValue: Object.freeze([1, 1, 1, 1]),
    section: 'Design',
    group: 'Pattern Colors',
    designParentGroup: 'palette' as const,
    order: 6,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_SKIN_PRIMARY_ID,
    label: 'Skin Primary',
    description: 'Sets the dominant cyan/teal color used only by HUM:N skin facets assigned to the primary authored palette role.',
    type: 'color' as const,
    defaultValue: Object.freeze([72 / 255, 240 / 255, 221 / 255, 1]),
    section: 'Design',
    group: 'Skin Colors',
    designParentGroup: 'palette' as const,
    order: 3,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_SKIN_SECONDARY_ID,
    label: 'Skin Secondary',
    description: 'Sets the contrasting magenta color used only by HUM:N skin facets assigned to the secondary authored palette role.',
    type: 'color' as const,
    defaultValue: Object.freeze([1, 61 / 255, 200 / 255, 1]),
    section: 'Design',
    group: 'Skin Colors',
    designParentGroup: 'palette' as const,
    order: 4,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_SKIN_ACCENT_ID,
    label: 'Skin Accent',
    description: 'Sets the rarer acid-green highlight color used only by HUM:N skin facets assigned to the accent authored palette role.',
    type: 'color' as const,
    defaultValue: Object.freeze([200 / 255, 1, 74 / 255, 1]),
    section: 'Design',
    group: 'Skin Colors',
    designParentGroup: 'palette' as const,
    order: 5,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_COLOR_SHIFT_AMOUNT_ID,
    label: 'Color Shift Amount',
    description: 'Controls the degree of palette role movement driven by high-frequency band energy. At 0, authored colors are completely stable.',
    type: 'float' as const,
    defaultValue: 0,
    min: 0,
    max: 1,
    step: 0.01,
    section: 'Design',
    group: 'Color Behavior',
    designParentGroup: 'palette' as const,
    order: 7,
    exposure: 'primary' as const,
    modulatable: true,
    choreographable: true,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
])

const CINEMA2_HUMN_FIGURE_PARAMETERS = Object.freeze([
  Object.freeze({
    id: CINEMA2_HUMN_MOTION_AMOUNT_ID,
    label: 'Motion Amount',
    description: 'Controls the authored low-to-medium HUM:N head, neck, shoulder, posture, and breathing motion while preserving the approved topology.',
    type: 'float' as const,
    defaultValue: 0,
    min: 0,
    max: 1,
    step: 0.01,
    section: 'Design',
    group: 'Motion',
    designParentGroup: 'design' as const,
    order: 1,
    exposure: 'primary' as const,
    modulatable: true,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_MOTION_RATE_ID,
    label: 'Motion Rate',
    description: 'Multiplies the phase of HUM:N authored native movement without changing its motion vocabulary.',
    type: 'enum' as const,
    defaultValue: '1x',
    options: Object.freeze([
      Object.freeze({ value: '1/2x', label: '1/2x' }),
      Object.freeze({ value: '1x', label: '1x' }),
      Object.freeze({ value: '2x', label: '2x' }),
      Object.freeze({ value: '4x', label: '4x' }),
    ]),
    section: 'Design',
    group: 'Motion',
    designParentGroup: 'design' as const,
    order: 2,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_LINE_PRESENCE_ID,
    label: 'Line Presence',
    description: 'Controls the visible presence of HUM:N topology lines while preserving the authored grid and geometry.',
    type: 'float' as const,
    defaultValue: 1,
    min: 0,
    max: 1,
    step: 0.01,
    section: 'Design',
    group: 'Figure Construction',
    designParentGroup: 'design' as const,
    order: 10,
    exposure: 'primary' as const,
    modulatable: true,
    choreographable: true,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_LINE_WEIGHT_ID,
    label: 'Line Weight',
    description: 'Changes the actual rendered thickness of HUM:N topology strokes without shifting the authored geometry.',
    type: 'float' as const,
    defaultValue: 1,
    min: 0.5,
    max: 2,
    step: 0.05,
    section: 'Design',
    group: 'Figure Construction',
    designParentGroup: 'design' as const,
    order: 11,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_FRAGMENTATION_ID,
    label: 'Fragmentation',
    description: 'Deterministically opens or closes authored topology segments without frame-to-frame reshuffling.',
    type: 'float' as const,
    defaultValue: 0.55,
    min: 0,
    max: 1,
    step: 0.01,
    section: 'Design',
    group: 'Figure Construction',
    designParentGroup: 'design' as const,
    order: 12,
    exposure: 'primary' as const,
    modulatable: true,
    choreographable: true,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_MESH_DETAIL_ID,
    label: 'Mesh Detail',
    description: 'Selects the authored HUM:N topology set eligible to render.',
    type: 'enum' as const,
    defaultValue: 'Reference',
    options: Object.freeze([
      Object.freeze({ value: 'Sparse', label: 'Sparse' }),
      Object.freeze({ value: 'Reference', label: 'Reference' }),
      Object.freeze({ value: 'Dense', label: 'Dense' }),
    ]),
    section: 'Design',
    group: 'Figure Construction',
    designParentGroup: 'design' as const,
    order: 13,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_FACET_FILL_ID,
    label: 'Facet Fill',
    description: 'Reveals authored polygonal skin facets beneath the HUM:N line network while preserving the user-owned base value for later intelligence modulation.',
    type: 'float' as const,
    defaultValue: 0,
    min: 0,
    max: 1,
    step: 0.01,
    section: 'Design',
    group: 'Figure Construction',
    designParentGroup: 'design' as const,
    order: 14,
    exposure: 'primary' as const,
    modulatable: true,
    choreographable: true,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_FILL_STYLE_ID,
    label: 'Fill Style',
    description: 'Selects the deterministic material treatment used by visible HUM:N skin facets.',
    type: 'enum' as const,
    defaultValue: 'Mixed',
    options: Object.freeze([
      Object.freeze({ value: 'Solid', label: 'Solid' }),
      Object.freeze({ value: 'Gradient', label: 'Gradient' }),
      Object.freeze({ value: 'Stripe', label: 'Stripe' }),
      Object.freeze({ value: 'Mixed', label: 'Mixed' }),
    ]),
    section: 'Design',
    group: 'Figure Construction',
    designParentGroup: 'design' as const,
    order: 15,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
])

const CINEMA2_HUMN_EFFECTS_PARAMETERS = Object.freeze([
  Object.freeze({
    id: CINEMA2_HUMN_FLICKER_AMOUNT_ID,
    label: 'Flicker Amount',
    description: 'Controls beat and downbeat-driven ghost line flicker intensity. At 0, rhythmic line events are visually absent.',
    type: 'float' as const,
    defaultValue: 0,
    min: 0,
    max: 1,
    step: 0.01,
    section: 'Design',
    group: 'Fragment Behavior',
    designParentGroup: 'effects' as const,
    order: 1,
    exposure: 'primary' as const,
    modulatable: true,
    choreographable: true,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_FRAGMENT_JITTER_ID,
    label: 'Fragment Jitter',
    description: 'Controls kick-driven local fragment displacement intensity. At 0, kick displacement is visually absent.',
    type: 'float' as const,
    defaultValue: 0,
    min: 0,
    max: 1,
    step: 0.01,
    section: 'Design',
    group: 'Fragment Behavior',
    designParentGroup: 'effects' as const,
    order: 2,
    exposure: 'primary' as const,
    modulatable: true,
    choreographable: true,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
])

/** Backward-compatible source export; the dedicated native HUM:N module owns it now. */
export const CINEMA2_HUMN_STATIC_FRAGMENT_SOURCE = CINEMA2_HUMN_FRAGMENT_SOURCE

export const CINEMA2_HUMN_PRESET_MANIFEST: Readonly<Cinema2NativePresetManifest> = Object.freeze({
  schemaId: CINEMA2_NATIVE_PRESET_SCHEMA_ID,
  schemaVersion: CINEMA2_NATIVE_PRESET_SCHEMA_VERSION,
  id: CINEMA2_HUMN_PRESET_ID,
  revision: 14,
  metadata: Object.freeze({
    name: 'HUM:N',
    description: 'A near-black sparse low-poly humanoid bust reconstructed from the approved fractured white wireframe silhouette with stronger facet hierarchy, faint emergence fragments, and a restrained technical grid.',
    tags: Object.freeze(['hum-n', 'native', 'humanoid', 'low-poly', 'wireframe', 'screen-space', 'keeper']),
  }),
  capabilities: Object.freeze([
    Object.freeze({ id: 'render.webgl2' as const, requirement: 'required' as const, purpose: 'Deterministic screen-space native HUM:N topology rendering.' }),
    Object.freeze({ id: 'audio.bands' as const, requirement: 'optional' as const, purpose: 'Continuous energy-driven line presence, fragmentation, facet fill, and palette color modulation.' }),
    Object.freeze({ id: 'music.beat' as const, requirement: 'optional' as const, purpose: 'Beat-driven ghost line flicker.' }),
    Object.freeze({ id: 'music.downbeat' as const, requirement: 'optional' as const, purpose: 'Downbeat-driven ghost emergence reveal.' }),
    Object.freeze({ id: 'music.rhythm-events' as const, requirement: 'optional' as const, purpose: 'Kick and snare-driven fragment behavior.' }),
    Object.freeze({ id: 'music.vocal-presence' as const, requirement: 'optional' as const, purpose: 'Vocal presence restraint of intelligence-added motion.' }),
    Object.freeze({ id: 'visual-director.significance' as const, requirement: 'optional' as const, purpose: 'Build choreography and ghost edge emphasis.' }),
  ]),
  parameters: Object.freeze([
    CINEMA2_QUALITY_MODE_PARAMETER,
    ...CINEMA2_HUMN_COMPOSITION_OUTPUT_PARAMETERS,
    ...CINEMA2_HUMN_FIGURE_PARAMETERS,
    ...CINEMA2_HUMN_PALETTE_PARAMETERS,
    ...CINEMA2_HUMN_EFFECTS_PARAMETERS,
  ]),
  modules: Object.freeze([Object.freeze({
    id: CINEMA2_HUMN_MODULE_ID,
    typeId: CINEMA2_HUMN_NATIVE_MODULE_TYPE_ID,
    version: CINEMA2_HUMN_NATIVE_MODULE_VERSION,
    enabled: true,
    parameters: Object.freeze({
      masterIntensity: 1,
      bpmSync: true,
      motionAmount: 0,
      motionRate: '1x',
      figureScale: 1,
      gridPresence: 1,
      linePresence: 1,
      lineWeight: 1,
      fragmentation: 0.55,
      meshDetail: 'Reference',
      facetFill: 0,
      fillStyle: 'Mixed',
      backgroundColor: Object.freeze([0, 0, 0, 1]),
      wireframeColor: Object.freeze([245 / 255, 247 / 255, 250 / 255, 1]),
      patternInk: Object.freeze([1, 1, 1, 1]),
      skinPrimary: Object.freeze([72 / 255, 240 / 255, 221 / 255, 1]),
      skinSecondary: Object.freeze([1, 61 / 255, 200 / 255, 1]),
      skinAccent: Object.freeze([200 / 255, 1, 74 / 255, 1]),
      masterReactivity: 0,
      colorShiftAmount: 0,
      flickerAmount: 0,
      fragmentJitter: 0,
      colorShiftHighBand: 0,
      colorShiftAirBand: 0,
      tensionMotionLift: 0,
      vocalMotionRestraint: 0,
      ghostEdgeEmphasis: 0,
      beatFlicker: 0,
      downbeatReveal: 0,
      kickJitter: 0,
      snareEyeCheek: 0,
    }),
    parameterBindings: Object.freeze({
      masterIntensity: cinema2Ref(CINEMA2_HUMN_MASTER_INTENSITY_ID),
      bpmSync: cinema2Ref(CINEMA2_HUMN_BPM_SYNC_ID),
      motionAmount: cinema2Ref(CINEMA2_HUMN_MOTION_AMOUNT_ID),
      motionRate: cinema2Ref(CINEMA2_HUMN_MOTION_RATE_ID),
      figureScale: cinema2Ref(CINEMA2_HUMN_FIGURE_SCALE_ID),
      gridPresence: cinema2Ref(CINEMA2_HUMN_GRID_PRESENCE_ID),
      linePresence: cinema2Ref(CINEMA2_HUMN_LINE_PRESENCE_ID),
      lineWeight: cinema2Ref(CINEMA2_HUMN_LINE_WEIGHT_ID),
      fragmentation: cinema2Ref(CINEMA2_HUMN_FRAGMENTATION_ID),
      meshDetail: cinema2Ref(CINEMA2_HUMN_MESH_DETAIL_ID),
      facetFill: cinema2Ref(CINEMA2_HUMN_FACET_FILL_ID),
      fillStyle: cinema2Ref(CINEMA2_HUMN_FILL_STYLE_ID),
      backgroundColor: cinema2Ref(CINEMA2_HUMN_BACKGROUND_ID),
      wireframeColor: cinema2Ref(CINEMA2_HUMN_WIREFRAME_ID),
      patternInk: cinema2Ref(CINEMA2_HUMN_PATTERN_INK_ID),
      skinPrimary: cinema2Ref(CINEMA2_HUMN_SKIN_PRIMARY_ID),
      skinSecondary: cinema2Ref(CINEMA2_HUMN_SKIN_SECONDARY_ID),
      skinAccent: cinema2Ref(CINEMA2_HUMN_SKIN_ACCENT_ID),
      masterReactivity: cinema2Ref(CINEMA2_HUMN_MASTER_REACTIVITY_ID),
      colorShiftAmount: cinema2Ref(CINEMA2_HUMN_COLOR_SHIFT_AMOUNT_ID),
      flickerAmount: cinema2Ref(CINEMA2_HUMN_FLICKER_AMOUNT_ID),
      fragmentJitter: cinema2Ref(CINEMA2_HUMN_FRAGMENT_JITTER_ID),
    }),
    config: Object.freeze({ label: 'HUM:N Sparse Wireframe Foundation' }),
  })]),
  choreography: Object.freeze({
    rules: Object.freeze([
      // Part B: Continuous appearance Audio Intelligence
      Object.freeze({
        id: choreographyRuleId('hum-n-overall-energy-line-presence'),
        priority: 10,
        source: Object.freeze({ signal: 'continuous' as const, capability: 'audio.bands' as const, path: 'audio.features.overallEnergy' as const, scale: -1, offset: 1, smoothingMs: 300 }),
        actions: Object.freeze([Object.freeze({
          id: choreographyActionId('hum-n-energy-lp-add'),
          target: Object.freeze({ kind: 'module' as const, ref: cinema2Ref(CINEMA2_HUMN_MODULE_ID), property: 'linePresence' }),
          operation: 'add' as const,
          value: -0.45,
        })]),
        strengthParameter: cinema2Ref(CINEMA2_HUMN_MASTER_REACTIVITY_ID),
      }),
      Object.freeze({
        id: choreographyRuleId('hum-n-complexity-fragmentation'),
        priority: 11,
        source: Object.freeze({ signal: 'continuous' as const, capability: 'audio.bands' as const, path: 'audio.features.complexity' as const, offset: -0.5, smoothingMs: 400 }),
        actions: Object.freeze([Object.freeze({
          id: choreographyActionId('hum-n-complexity-frag-add'),
          target: Object.freeze({ kind: 'module' as const, ref: cinema2Ref(CINEMA2_HUMN_MODULE_ID), property: 'fragmentation' }),
          operation: 'add' as const,
          value: 0.36,
        })]),
        strengthParameter: cinema2Ref(CINEMA2_HUMN_MASTER_REACTIVITY_ID),
      }),
      Object.freeze({
        id: choreographyRuleId('hum-n-track-energy-facet-fill'),
        priority: 12,
        source: Object.freeze({ signal: 'continuous' as const, capability: 'audio.bands' as const, path: 'audio.features.trackEnergy' as const, smoothingMs: 200 }),
        actions: Object.freeze([Object.freeze({
          id: choreographyActionId('hum-n-energy-facet-add'),
          target: Object.freeze({ kind: 'module' as const, ref: cinema2Ref(CINEMA2_HUMN_MODULE_ID), property: 'facetFill' }),
          operation: 'add' as const,
          value: 0.35,
        })]),
        strengthParameter: cinema2Ref(CINEMA2_HUMN_MASTER_REACTIVITY_ID),
      }),
      // Part C: High + Air → palette color shift
      Object.freeze({
        id: choreographyRuleId('hum-n-high-band-color-shift'),
        priority: 13,
        source: Object.freeze({ signal: 'continuous' as const, capability: 'audio.bands' as const, path: 'audio.bands.high' as const, smoothingMs: 100 }),
        actions: Object.freeze([Object.freeze({
          id: choreographyActionId('hum-n-high-color-replace'),
          target: Object.freeze({ kind: 'module' as const, ref: cinema2Ref(CINEMA2_HUMN_MODULE_ID), property: 'colorShiftHighBand' }),
          operation: 'replace' as const,
          value: 1,
        })]),
        strengthParameter: cinema2Ref(CINEMA2_HUMN_MASTER_REACTIVITY_ID),
      }),
      Object.freeze({
        id: choreographyRuleId('hum-n-air-band-color-shift'),
        priority: 14,
        source: Object.freeze({ signal: 'continuous' as const, capability: 'audio.bands' as const, path: 'audio.bands.air' as const, smoothingMs: 80 }),
        actions: Object.freeze([Object.freeze({
          id: choreographyActionId('hum-n-air-color-replace'),
          target: Object.freeze({ kind: 'module' as const, ref: cinema2Ref(CINEMA2_HUMN_MODULE_ID), property: 'colorShiftAirBand' }),
          operation: 'replace' as const,
          value: 1,
        })]),
        strengthParameter: cinema2Ref(CINEMA2_HUMN_MASTER_REACTIVITY_ID),
      }),
      // Part D: Tension motion lift + vocal restraint
      Object.freeze({
        id: choreographyRuleId('hum-n-tension-motion-lift'),
        priority: 15,
        source: Object.freeze({ signal: 'continuous' as const, capability: 'audio.bands' as const, path: 'audio.features.tension' as const, smoothingMs: 250 }),
        actions: Object.freeze([Object.freeze({
          id: choreographyActionId('hum-n-tension-motion-replace'),
          target: Object.freeze({ kind: 'module' as const, ref: cinema2Ref(CINEMA2_HUMN_MODULE_ID), property: 'tensionMotionLift' }),
          operation: 'replace' as const,
          value: 0.25,
        })]),
        strengthParameter: cinema2Ref(CINEMA2_HUMN_MASTER_REACTIVITY_ID),
      }),
      Object.freeze({
        id: choreographyRuleId('hum-n-vocal-motion-restraint'),
        priority: 16,
        source: Object.freeze({ signal: 'continuous' as const, capability: 'music.vocal-presence' as const, path: 'audio.features.vocalPresence' as const, smoothingMs: 300 }),
        actions: Object.freeze([Object.freeze({
          id: choreographyActionId('hum-n-vocal-restraint-replace'),
          target: Object.freeze({ kind: 'module' as const, ref: cinema2Ref(CINEMA2_HUMN_MODULE_ID), property: 'vocalMotionRestraint' }),
          operation: 'replace' as const,
          value: 0.25,
        })]),
        strengthParameter: cinema2Ref(CINEMA2_HUMN_MASTER_REACTIVITY_ID),
      }),
      // Part G: Build choreography
      Object.freeze({
        id: choreographyRuleId('hum-n-build-facet-fill'),
        priority: 20,
        source: Object.freeze({ signal: 'continuous' as const, capability: 'visual-director.significance' as const, path: 'director.build' as const, smoothingMs: 500 }),
        actions: Object.freeze([Object.freeze({
          id: choreographyActionId('hum-n-build-facet-add'),
          target: Object.freeze({ kind: 'module' as const, ref: cinema2Ref(CINEMA2_HUMN_MODULE_ID), property: 'facetFill' }),
          operation: 'add' as const,
          value: 0.25,
        })]),
        strengthParameter: cinema2Ref(CINEMA2_HUMN_MASTER_REACTIVITY_ID),
      }),
      Object.freeze({
        id: choreographyRuleId('hum-n-build-fragmentation'),
        priority: 21,
        source: Object.freeze({ signal: 'continuous' as const, capability: 'visual-director.significance' as const, path: 'director.build' as const, smoothingMs: 500 }),
        actions: Object.freeze([Object.freeze({
          id: choreographyActionId('hum-n-build-frag-add'),
          target: Object.freeze({ kind: 'module' as const, ref: cinema2Ref(CINEMA2_HUMN_MODULE_ID), property: 'fragmentation' }),
          operation: 'add' as const,
          value: -0.12,
        })]),
        strengthParameter: cinema2Ref(CINEMA2_HUMN_MASTER_REACTIVITY_ID),
      }),
      Object.freeze({
        id: choreographyRuleId('hum-n-build-motion-amount'),
        priority: 22,
        source: Object.freeze({ signal: 'continuous' as const, capability: 'visual-director.significance' as const, path: 'director.build' as const, smoothingMs: 500 }),
        actions: Object.freeze([Object.freeze({
          id: choreographyActionId('hum-n-build-motion-add'),
          target: Object.freeze({ kind: 'module' as const, ref: cinema2Ref(CINEMA2_HUMN_MODULE_ID), property: 'motionAmount' }),
          operation: 'add' as const,
          value: 0.15,
        })]),
        strengthParameter: cinema2Ref(CINEMA2_HUMN_MASTER_REACTIVITY_ID),
      }),
      Object.freeze({
        id: choreographyRuleId('hum-n-build-color-shift'),
        priority: 23,
        source: Object.freeze({ signal: 'continuous' as const, capability: 'visual-director.significance' as const, path: 'director.build' as const, smoothingMs: 500 }),
        actions: Object.freeze([Object.freeze({
          id: choreographyActionId('hum-n-build-color-add'),
          target: Object.freeze({ kind: 'module' as const, ref: cinema2Ref(CINEMA2_HUMN_MODULE_ID), property: 'colorShiftAmount' }),
          operation: 'add' as const,
          value: 0.20,
        })]),
        strengthParameter: cinema2Ref(CINEMA2_HUMN_MASTER_REACTIVITY_ID),
      }),
      Object.freeze({
        id: choreographyRuleId('hum-n-build-ghost-edge'),
        priority: 24,
        source: Object.freeze({ signal: 'continuous' as const, capability: 'visual-director.significance' as const, path: 'director.build' as const, smoothingMs: 500 }),
        actions: Object.freeze([Object.freeze({
          id: choreographyActionId('hum-n-build-ghost-replace'),
          target: Object.freeze({ kind: 'module' as const, ref: cinema2Ref(CINEMA2_HUMN_MODULE_ID), property: 'ghostEdgeEmphasis' }),
          operation: 'replace' as const,
          value: 0.20,
        })]),
        strengthParameter: cinema2Ref(CINEMA2_HUMN_MASTER_REACTIVITY_ID),
      }),
      // Part F: Rhythmic fragment events
      Object.freeze({
        id: choreographyRuleId('hum-n-beat-flicker'),
        priority: 30,
        source: Object.freeze({ signal: 'beat' as const, capability: 'music.beat' as const }),
        actions: Object.freeze([Object.freeze({
          id: choreographyActionId('hum-n-beat-flicker-envelope'),
          target: Object.freeze({ kind: 'module' as const, ref: cinema2Ref(CINEMA2_HUMN_MODULE_ID), property: 'beatFlicker' }),
          operation: 'envelope' as const,
          value: 1,
          composition: 'replace' as const,
          envelope: Object.freeze({ attack: 0, hold: 0.01, release: 0.18, unit: 'seconds' as const }),
          retrigger: 'restart' as const,
        })]),
      }),
      Object.freeze({
        id: choreographyRuleId('hum-n-downbeat-reveal'),
        priority: 31,
        source: Object.freeze({ signal: 'downbeat' as const, capability: 'music.downbeat' as const }),
        actions: Object.freeze([Object.freeze({
          id: choreographyActionId('hum-n-downbeat-reveal-envelope'),
          target: Object.freeze({ kind: 'module' as const, ref: cinema2Ref(CINEMA2_HUMN_MODULE_ID), property: 'downbeatReveal' }),
          operation: 'envelope' as const,
          value: 1,
          composition: 'replace' as const,
          envelope: Object.freeze({ attack: 0, hold: 0.025, release: 0.25, unit: 'seconds' as const }),
          retrigger: 'restart' as const,
        })]),
      }),
      Object.freeze({
        id: choreographyRuleId('hum-n-kick-jitter'),
        priority: 32,
        source: Object.freeze({ signal: 'kick' as const, capability: 'music.rhythm-events' as const }),
        actions: Object.freeze([Object.freeze({
          id: choreographyActionId('hum-n-kick-jitter-envelope'),
          target: Object.freeze({ kind: 'module' as const, ref: cinema2Ref(CINEMA2_HUMN_MODULE_ID), property: 'kickJitter' }),
          operation: 'envelope' as const,
          value: 1,
          composition: 'replace' as const,
          envelope: Object.freeze({ attack: 0, hold: 0.01, release: 0.25, unit: 'seconds' as const }),
          retrigger: 'restart' as const,
        })]),
      }),
      Object.freeze({
        id: choreographyRuleId('hum-n-snare-eye-cheek'),
        priority: 33,
        source: Object.freeze({ signal: 'snare' as const, capability: 'music.rhythm-events' as const }),
        actions: Object.freeze([Object.freeze({
          id: choreographyActionId('hum-n-snare-eye-cheek-envelope'),
          target: Object.freeze({ kind: 'module' as const, ref: cinema2Ref(CINEMA2_HUMN_MODULE_ID), property: 'snareEyeCheek' }),
          operation: 'envelope' as const,
          value: 1,
          composition: 'replace' as const,
          envelope: Object.freeze({ attack: 0, hold: 0.01, release: 0.125, unit: 'seconds' as const }),
          retrigger: 'restart' as const,
        })]),
      }),
    ]),
  }),
  scene: Object.freeze({
    nodes: Object.freeze([
      Object.freeze({ id: CINEMA2_HUMN_ROOT_NODE_ID, kind: 'group' as const, coordinateSpace: 'normalized-screen' as const, visible: true }),
      Object.freeze({ id: CINEMA2_HUMN_MODULE_NODE_ID, kind: 'module' as const, parent: cinema2Ref(CINEMA2_HUMN_ROOT_NODE_ID), module: cinema2Ref(CINEMA2_HUMN_MODULE_ID), visible: true }),
    ]),
  }),
  layers: Object.freeze([Object.freeze({
    id: CINEMA2_HUMN_LAYER_ID,
    label: 'HUM:N Emergence',
    source: cinema2Ref(CINEMA2_HUMN_ROOT_NODE_ID),
    visible: true,
    opacity: 1,
    blendMode: 'normal' as const,
    depthPolicy: 'disabled' as const,
    order: 0,
  })]),
})
