import {
  CINEMA2_NATIVE_PRESET_SCHEMA_ID,
  CINEMA2_NATIVE_PRESET_SCHEMA_VERSION,
  cinema2NamespacedId,
  cinema2Ref,
  cinema2StableId,
  type Cinema2LayerId,
  type Cinema2ModuleId,
  type Cinema2ParameterId,
  type Cinema2NativePresetManifest,
  type Cinema2PresetId,
  type Cinema2SceneNodeId,
} from '../contracts/Cinema2NativePresetManifest'
import {
  CINEMA2_HUMN_FRAGMENT_SOURCE,
  CINEMA2_HUMN_NATIVE_MODULE_TYPE_ID,
  CINEMA2_HUMN_NATIVE_MODULE_VERSION,
} from '../modules/Cinema2HumNNativeModule'
import { CINEMA2_QUALITY_MODE_PARAMETER } from '../parameters/Cinema2PerformanceParameters'

export const CINEMA2_HUMN_PRESET_ID = cinema2NamespacedId<Cinema2PresetId>('drmvyz.cinema2.hum-n')
export const CINEMA2_HUMN_MODULE_ID = cinema2StableId<Cinema2ModuleId>('hum-n-emergence')
export const CINEMA2_HUMN_ROOT_NODE_ID = cinema2StableId<Cinema2SceneNodeId>('hum-n-root')
export const CINEMA2_HUMN_MODULE_NODE_ID = cinema2StableId<Cinema2SceneNodeId>('hum-n-emergence-node')
export const CINEMA2_HUMN_LAYER_ID = cinema2StableId<Cinema2LayerId>('hum-n-emergence-layer')

export const CINEMA2_HUMN_LINE_PRESENCE_ID = cinema2StableId<Cinema2ParameterId>('hum-n-line-presence')
export const CINEMA2_HUMN_LINE_WEIGHT_ID = cinema2StableId<Cinema2ParameterId>('hum-n-line-weight')
export const CINEMA2_HUMN_FRAGMENTATION_ID = cinema2StableId<Cinema2ParameterId>('hum-n-fragmentation')
export const CINEMA2_HUMN_MESH_DETAIL_ID = cinema2StableId<Cinema2ParameterId>('hum-n-mesh-detail')
export const CINEMA2_HUMN_FACET_FILL_ID = cinema2StableId<Cinema2ParameterId>('hum-n-facet-fill')
export const CINEMA2_HUMN_FILL_STYLE_ID = cinema2StableId<Cinema2ParameterId>('hum-n-fill-style')
export const CINEMA2_HUMN_MASTER_INTENSITY_ID = cinema2StableId<Cinema2ParameterId>('hum-n-master-intensity')
export const CINEMA2_HUMN_BPM_SYNC_ID = cinema2StableId<Cinema2ParameterId>('hum-n-bpm-sync')
export const CINEMA2_HUMN_MOTION_AMOUNT_ID = cinema2StableId<Cinema2ParameterId>('hum-n-motion-amount')
export const CINEMA2_HUMN_MOTION_RATE_ID = cinema2StableId<Cinema2ParameterId>('hum-n-motion-rate')
export const CINEMA2_HUMN_FIGURE_SCALE_ID = cinema2StableId<Cinema2ParameterId>('hum-n-figure-scale')
export const CINEMA2_HUMN_GRID_PRESENCE_ID = cinema2StableId<Cinema2ParameterId>('hum-n-grid-presence')
export const CINEMA2_HUMN_BACKGROUND_ID = cinema2StableId<Cinema2ParameterId>('hum-n-background')
export const CINEMA2_HUMN_WIREFRAME_ID = cinema2StableId<Cinema2ParameterId>('hum-n-wireframe')
export const CINEMA2_HUMN_PATTERN_INK_ID = cinema2StableId<Cinema2ParameterId>('hum-n-pattern-ink')
export const CINEMA2_HUMN_SKIN_PRIMARY_ID = cinema2StableId<Cinema2ParameterId>('hum-n-skin-primary')
export const CINEMA2_HUMN_SKIN_SECONDARY_ID = cinema2StableId<Cinema2ParameterId>('hum-n-skin-secondary')
export const CINEMA2_HUMN_SKIN_ACCENT_ID = cinema2StableId<Cinema2ParameterId>('hum-n-skin-accent')

const CINEMA2_HUMN_COMPOSITION_OUTPUT_PARAMETERS = Object.freeze([
  Object.freeze({
    id: CINEMA2_HUMN_MASTER_INTENSITY_ID,
    label: 'Master Intensity',
    description: 'Controls the final HUM:N figure and facet output strength without changing the technical stage or grid.',
    type: 'float' as const,
    defaultValue: 1,
    min: 0,
    max: 1,
    step: 0.01,
    section: 'Design',
    designParentGroup: 'master-controls' as const,
    order: 1,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_BPM_SYNC_ID,
    label: 'BPM Sync',
    description: 'Uses the shared Cinema 2.0 synced-motion clock for HUM:N native movement. This remains a hard user-owned authorization.',
    type: 'boolean' as const,
    defaultValue: true,
    section: 'Design',
    designParentGroup: 'master-controls' as const,
    order: 2,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_FIGURE_SCALE_ID,
    label: 'Figure Scale',
    description: 'Uniformly scales the complete HUM:N figure around the approved composition anchor while preserving its proportions.',
    type: 'float' as const,
    defaultValue: 1,
    min: 0.7,
    max: 1.3,
    step: 0.01,
    section: 'Design',
    group: 'Composition',
    designParentGroup: 'design' as const,
    order: 1,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_GRID_PRESENCE_ID,
    label: 'Grid Presence',
    description: 'Controls only the restrained technical background grid while leaving the near-black stage intact.',
    type: 'float' as const,
    defaultValue: 1,
    min: 0,
    max: 1,
    step: 0.01,
    section: 'Design',
    group: 'Stage',
    designParentGroup: 'design' as const,
    order: 2,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
])

const CINEMA2_HUMN_PALETTE_PARAMETERS = Object.freeze([
  Object.freeze({
    id: CINEMA2_HUMN_BACKGROUND_ID,
    label: 'Background',
    description: 'Sets only the HUM:N stage/background surface color without recoloring the grid, figure line art, or facet pattern ink.',
    type: 'color' as const,
    defaultValue: Object.freeze([0, 0, 0, 1]),
    section: 'Design',
    group: 'Stage Colors',
    designParentGroup: 'palette' as const,
    order: 1,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_WIREFRAME_ID,
    label: 'Wireframe',
    description: 'Sets the primary HUM:N topology line color while preserving authored line hierarchy and leaving Pattern Ink independent.',
    type: 'color' as const,
    defaultValue: Object.freeze([245 / 255, 247 / 255, 250 / 255, 1]),
    section: 'Design',
    group: 'Figure Colors',
    designParentGroup: 'palette' as const,
    order: 2,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_PATTERN_INK_ID,
    label: 'Pattern Ink',
    description: 'Sets the bright ink used by Stripe and Mixed skin-facet graphics without recoloring the stage or topology lines.',
    type: 'color' as const,
    defaultValue: Object.freeze([1, 1, 1, 1]),
    section: 'Design',
    group: 'Pattern Colors',
    designParentGroup: 'palette' as const,
    order: 6,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_SKIN_PRIMARY_ID,
    label: 'Skin Primary',
    description: 'Sets the dominant cyan/teal color used only by HUM:N skin facets assigned to the primary authored palette role.',
    type: 'color' as const,
    defaultValue: Object.freeze([72 / 255, 240 / 255, 221 / 255, 1]),
    section: 'Design',
    group: 'Skin Colors',
    designParentGroup: 'palette' as const,
    order: 3,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_SKIN_SECONDARY_ID,
    label: 'Skin Secondary',
    description: 'Sets the contrasting magenta color used only by HUM:N skin facets assigned to the secondary authored palette role.',
    type: 'color' as const,
    defaultValue: Object.freeze([1, 61 / 255, 200 / 255, 1]),
    section: 'Design',
    group: 'Skin Colors',
    designParentGroup: 'palette' as const,
    order: 4,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_SKIN_ACCENT_ID,
    label: 'Skin Accent',
    description: 'Sets the rarer acid-green highlight color used only by HUM:N skin facets assigned to the accent authored palette role.',
    type: 'color' as const,
    defaultValue: Object.freeze([200 / 255, 1, 74 / 255, 1]),
    section: 'Design',
    group: 'Skin Colors',
    designParentGroup: 'palette' as const,
    order: 5,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
])

const CINEMA2_HUMN_FIGURE_PARAMETERS = Object.freeze([
  Object.freeze({
    id: CINEMA2_HUMN_MOTION_AMOUNT_ID,
    label: 'Motion Amount',
    description: 'Controls the authored low-to-medium HUM:N head, neck, shoulder, posture, and breathing motion while preserving the approved topology.',
    type: 'float' as const,
    defaultValue: 0,
    min: 0,
    max: 1,
    step: 0.01,
    section: 'Design',
    group: 'Motion',
    designParentGroup: 'design' as const,
    order: 1,
    exposure: 'primary' as const,
    modulatable: true,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_MOTION_RATE_ID,
    label: 'Motion Rate',
    description: 'Multiplies the phase of HUM:N authored native movement without changing its motion vocabulary.',
    type: 'enum' as const,
    defaultValue: '1x',
    options: Object.freeze([
      Object.freeze({ value: '1/2x', label: '1/2x' }),
      Object.freeze({ value: '1x', label: '1x' }),
      Object.freeze({ value: '2x', label: '2x' }),
      Object.freeze({ value: '4x', label: '4x' }),
    ]),
    section: 'Design',
    group: 'Motion',
    designParentGroup: 'design' as const,
    order: 2,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_LINE_PRESENCE_ID,
    label: 'Line Presence',
    description: 'Controls the visible presence of HUM:N topology lines while preserving the authored grid and geometry.',
    type: 'float' as const,
    defaultValue: 1,
    min: 0,
    max: 1,
    step: 0.01,
    section: 'Design',
    group: 'Figure Construction',
    designParentGroup: 'design' as const,
    order: 10,
    exposure: 'primary' as const,
    modulatable: true,
    choreographable: true,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_LINE_WEIGHT_ID,
    label: 'Line Weight',
    description: 'Changes the actual rendered thickness of HUM:N topology strokes without shifting the authored geometry.',
    type: 'float' as const,
    defaultValue: 1,
    min: 0.5,
    max: 2,
    step: 0.05,
    section: 'Design',
    group: 'Figure Construction',
    designParentGroup: 'design' as const,
    order: 11,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_FRAGMENTATION_ID,
    label: 'Fragmentation',
    description: 'Deterministically opens or closes authored topology segments without frame-to-frame reshuffling.',
    type: 'float' as const,
    defaultValue: 0.55,
    min: 0,
    max: 1,
    step: 0.01,
    section: 'Design',
    group: 'Figure Construction',
    designParentGroup: 'design' as const,
    order: 12,
    exposure: 'primary' as const,
    modulatable: true,
    choreographable: true,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_MESH_DETAIL_ID,
    label: 'Mesh Detail',
    description: 'Selects the authored HUM:N topology set eligible to render.',
    type: 'enum' as const,
    defaultValue: 'Reference',
    options: Object.freeze([
      Object.freeze({ value: 'Sparse', label: 'Sparse' }),
      Object.freeze({ value: 'Reference', label: 'Reference' }),
      Object.freeze({ value: 'Dense', label: 'Dense' }),
    ]),
    section: 'Design',
    group: 'Figure Construction',
    designParentGroup: 'design' as const,
    order: 13,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_FACET_FILL_ID,
    label: 'Facet Fill',
    description: 'Reveals authored polygonal skin facets beneath the HUM:N line network while preserving the user-owned base value for later intelligence modulation.',
    type: 'float' as const,
    defaultValue: 0,
    min: 0,
    max: 1,
    step: 0.01,
    section: 'Design',
    group: 'Figure Construction',
    designParentGroup: 'design' as const,
    order: 14,
    exposure: 'primary' as const,
    modulatable: true,
    choreographable: true,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
  Object.freeze({
    id: CINEMA2_HUMN_FILL_STYLE_ID,
    label: 'Fill Style',
    description: 'Selects the deterministic material treatment used by visible HUM:N skin facets.',
    type: 'enum' as const,
    defaultValue: 'Mixed',
    options: Object.freeze([
      Object.freeze({ value: 'Solid', label: 'Solid' }),
      Object.freeze({ value: 'Gradient', label: 'Gradient' }),
      Object.freeze({ value: 'Stripe', label: 'Stripe' }),
      Object.freeze({ value: 'Mixed', label: 'Mixed' }),
    ]),
    section: 'Design',
    group: 'Figure Construction',
    designParentGroup: 'design' as const,
    order: 15,
    exposure: 'primary' as const,
    modulatable: false,
    choreographable: false,
    automatable: false,
    persistence: 'preset' as const,
    reset: 'authored-default' as const,
  }),
])

/** Backward-compatible source export; the dedicated native HUM:N module owns it now. */
export const CINEMA2_HUMN_STATIC_FRAGMENT_SOURCE = CINEMA2_HUMN_FRAGMENT_SOURCE

export const CINEMA2_HUMN_PRESET_MANIFEST: Readonly<Cinema2NativePresetManifest> = Object.freeze({
  schemaId: CINEMA2_NATIVE_PRESET_SCHEMA_ID,
  schemaVersion: CINEMA2_NATIVE_PRESET_SCHEMA_VERSION,
  id: CINEMA2_HUMN_PRESET_ID,
  revision: 10,
  metadata: Object.freeze({
    name: 'HUM:N',
    description: 'A near-black sparse low-poly humanoid bust reconstructed from the approved fractured white wireframe silhouette with stronger facet hierarchy, faint emergence fragments, and a restrained technical grid.',
    tags: Object.freeze(['hum-n', 'native', 'humanoid', 'low-poly', 'wireframe', 'screen-space', 'keeper']),
  }),
  capabilities: Object.freeze([
    Object.freeze({ id: 'render.webgl2' as const, requirement: 'required' as const, purpose: 'Deterministic screen-space native HUM:N topology rendering.' }),
  ]),
  parameters: Object.freeze([
    CINEMA2_QUALITY_MODE_PARAMETER,
    ...CINEMA2_HUMN_COMPOSITION_OUTPUT_PARAMETERS,
    ...CINEMA2_HUMN_FIGURE_PARAMETERS,
    ...CINEMA2_HUMN_PALETTE_PARAMETERS,
  ]),
  modules: Object.freeze([Object.freeze({
    id: CINEMA2_HUMN_MODULE_ID,
    typeId: CINEMA2_HUMN_NATIVE_MODULE_TYPE_ID,
    version: CINEMA2_HUMN_NATIVE_MODULE_VERSION,
    enabled: true,
    parameters: Object.freeze({
      masterIntensity: 1,
      bpmSync: true,
      motionAmount: 0,
      motionRate: '1x',
      figureScale: 1,
      gridPresence: 1,
      linePresence: 1,
      lineWeight: 1,
      fragmentation: 0.55,
      meshDetail: 'Reference',
      facetFill: 0,
      fillStyle: 'Mixed',
      backgroundColor: Object.freeze([0, 0, 0, 1]),
      wireframeColor: Object.freeze([245 / 255, 247 / 255, 250 / 255, 1]),
      patternInk: Object.freeze([1, 1, 1, 1]),
      skinPrimary: Object.freeze([72 / 255, 240 / 255, 221 / 255, 1]),
      skinSecondary: Object.freeze([1, 61 / 255, 200 / 255, 1]),
      skinAccent: Object.freeze([200 / 255, 1, 74 / 255, 1]),
    }),
    parameterBindings: Object.freeze({
      masterIntensity: cinema2Ref(CINEMA2_HUMN_MASTER_INTENSITY_ID),
      bpmSync: cinema2Ref(CINEMA2_HUMN_BPM_SYNC_ID),
      motionAmount: cinema2Ref(CINEMA2_HUMN_MOTION_AMOUNT_ID),
      motionRate: cinema2Ref(CINEMA2_HUMN_MOTION_RATE_ID),
      figureScale: cinema2Ref(CINEMA2_HUMN_FIGURE_SCALE_ID),
      gridPresence: cinema2Ref(CINEMA2_HUMN_GRID_PRESENCE_ID),
      linePresence: cinema2Ref(CINEMA2_HUMN_LINE_PRESENCE_ID),
      lineWeight: cinema2Ref(CINEMA2_HUMN_LINE_WEIGHT_ID),
      fragmentation: cinema2Ref(CINEMA2_HUMN_FRAGMENTATION_ID),
      meshDetail: cinema2Ref(CINEMA2_HUMN_MESH_DETAIL_ID),
      facetFill: cinema2Ref(CINEMA2_HUMN_FACET_FILL_ID),
      fillStyle: cinema2Ref(CINEMA2_HUMN_FILL_STYLE_ID),
      backgroundColor: cinema2Ref(CINEMA2_HUMN_BACKGROUND_ID),
      wireframeColor: cinema2Ref(CINEMA2_HUMN_WIREFRAME_ID),
      patternInk: cinema2Ref(CINEMA2_HUMN_PATTERN_INK_ID),
      skinPrimary: cinema2Ref(CINEMA2_HUMN_SKIN_PRIMARY_ID),
      skinSecondary: cinema2Ref(CINEMA2_HUMN_SKIN_SECONDARY_ID),
      skinAccent: cinema2Ref(CINEMA2_HUMN_SKIN_ACCENT_ID),
    }),
    config: Object.freeze({ label: 'HUM:N Sparse Wireframe Foundation' }),
  })]),
  scene: Object.freeze({
    nodes: Object.freeze([
      Object.freeze({ id: CINEMA2_HUMN_ROOT_NODE_ID, kind: 'group' as const, coordinateSpace: 'normalized-screen' as const, visible: true }),
      Object.freeze({ id: CINEMA2_HUMN_MODULE_NODE_ID, kind: 'module' as const, parent: cinema2Ref(CINEMA2_HUMN_ROOT_NODE_ID), module: cinema2Ref(CINEMA2_HUMN_MODULE_ID), visible: true }),
    ]),
  }),
  layers: Object.freeze([Object.freeze({
    id: CINEMA2_HUMN_LAYER_ID,
    label: 'HUM:N Emergence',
    source: cinema2Ref(CINEMA2_HUMN_ROOT_NODE_ID),
    visible: true,
    opacity: 1,
    blendMode: 'normal' as const,
    depthPolicy: 'disabled' as const,
    order: 0,
  })]),
})
