// GENERATED by `npm run assets:build` from assets/cinema2/*/asset.json. Do not edit by hand.
import type { Cinema2GeneratedAssetRecord } from './Cinema2GeneratedAssetTypes'

export const CINEMA2_ASSET_RECORDS = [
  {
    "id": "cinema2-atl-hoe",
    "kind": "model",
    "compression": "none",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/models/atl-hoe.glb",
        "bytes": 1323800,
        "triangles": 22464
      }
    },
    "gpuBytes": {
      "high": 1309320,
      "medium": 1309320,
      "low": 1309320
    }
  },
  {
    "id": "cinema2-conduit-chamber",
    "kind": "model",
    "compression": "none",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/models/conduit-chamber.glb",
        "bytes": 7059684,
        "triangles": 142196
      }
    },
    "gpuBytes": {
      "high": 7050680,
      "medium": 7050680,
      "low": 7050680
    }
  },
  {
    "id": "cinema2-conduit-tubes",
    "kind": "model",
    "compression": "none",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/models/conduit-tubes.glb",
        "bytes": 3287340,
        "triangles": 61984
      }
    },
    "gpuBytes": {
      "high": 3266504,
      "medium": 3266504,
      "low": 3266504
    }
  },
  {
    "id": "cinema2-conduit-wordmark",
    "kind": "model",
    "compression": "none",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/models/conduit-wordmark.glb",
        "bytes": 2946436,
        "triangles": 57882
      }
    },
    "gpuBytes": {
      "high": 2938540,
      "medium": 2938540,
      "low": 2938540
    }
  },
  {
    "id": "cinema2-dvydrm-logo",
    "kind": "model",
    "compression": "none",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/models/dvydrm-logo.glb",
        "bytes": 1136736,
        "triangles": 31216
      }
    },
    "gpuBytes": {
      "high": 1134744,
      "medium": 1134744,
      "low": 1134744
    }
  },
  {
    "id": "cinema2-dvydrm-logo-faceted",
    "kind": "model",
    "compression": "none",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/models/dvydrm-logo-faceted.glb",
        "bytes": 1013284,
        "triangles": 23902
      }
    },
    "gpuBytes": {
      "high": 1012052,
      "medium": 1012052,
      "low": 1012052
    }
  },
  {
    "id": "cinema2-golden-roots",
    "kind": "model",
    "compression": "none",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/models/golden-roots.glb",
        "bytes": 2643932,
        "triangles": 83912
      }
    },
    "gpuBytes": {
      "high": 2639792,
      "medium": 2639792,
      "low": 2639792
    }
  },
  {
    "id": "cinema2-reference-torus-knot",
    "kind": "model",
    "compression": "meshopt",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/models/reference-torus-knot.glb",
        "bytes": 158960,
        "triangles": 24000
      }
    },
    "gpuBytes": {
      "high": 341456,
      "medium": 341456,
      "low": 341456
    }
  },
  {
    "id": "cinema2-reliquary-trees",
    "kind": "model",
    "compression": "none",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/models/reliquary-trees.glb",
        "bytes": 7655040,
        "triangles": 133476
      }
    },
    "gpuBytes": {
      "high": 9957578,
      "medium": 9957578,
      "low": 9957578
    }
  },
  {
    "id": "cinema2-say-it-glyphs",
    "kind": "model",
    "compression": "none",
    "license": "OFL-1.1",
    "attribution": "Anton Regular, Copyright 2020 The Anton Project Authors, licensed under the SIL Open Font License 1.1. License text ships at public/cinema2/licenses/Anton-OFL-1.1.txt.",
    "files": {
      "high": {
        "url": "/cinema2/models/say-it-glyphs-v1.glb",
        "bytes": 1963748,
        "triangles": 57482
      }
    },
    "gpuBytes": {
      "high": 1887064,
      "medium": 1887064,
      "low": 1887064
    }
  },
  {
    "id": "cinema2-smoke-sprites",
    "kind": "texture",
    "layout": "sprite-sheet-rgba",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/textures/smoke-sprites-512.webp",
        "bytes": 121430,
        "width": 512,
        "height": 512
      },
      "low": {
        "url": "/cinema2/textures/smoke-sprites-256.webp",
        "bytes": 40712,
        "width": 256,
        "height": 256
      }
    },
    "gpuBytes": {
      "high": 1398101,
      "medium": 1398101,
      "low": 349525
    }
  },
  {
    "id": "cinema2-smoke-volume",
    "kind": "texture",
    "layout": "noise-volume-rgba",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/textures/smoke-volume-64.webp",
        "bytes": 660238,
        "width": 64,
        "height": 64,
        "depth": 64
      },
      "low": {
        "url": "/cinema2/textures/smoke-volume-32.webp",
        "bytes": 103852,
        "width": 32,
        "height": 32,
        "depth": 32
      }
    },
    "gpuBytes": {
      "high": 1398101,
      "medium": 1398101,
      "low": 174763
    }
  },
  {
    "id": "cinema2-studio-environment",
    "kind": "environment",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/environments/studio-1024.hdr",
        "bytes": 152066,
        "width": 1024,
        "height": 512
      },
      "low": {
        "url": "/cinema2/environments/studio-512.hdr",
        "bytes": 42279,
        "width": 512,
        "height": 256
      }
    },
    "gpuBytes": {
      "high": 4194304,
      "medium": 4194304,
      "low": 4194304
    }
  },
  {
    "id": "cinema2-studio-environment-gem",
    "kind": "environment",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/environments/studio-gem-1024.hdr",
        "bytes": 72608,
        "width": 1024,
        "height": 512
      },
      "low": {
        "url": "/cinema2/environments/studio-gem-512.hdr",
        "bytes": 22233,
        "width": 512,
        "height": 256
      }
    },
    "gpuBytes": {
      "high": 4194304,
      "medium": 4194304,
      "low": 4194304
    }
  },
  {
    "id": "cinema2-studio-environment-neutral",
    "kind": "environment",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/environments/studio-neutral-1024.hdr",
        "bytes": 148259,
        "width": 1024,
        "height": 512
      },
      "low": {
        "url": "/cinema2/environments/studio-neutral-512.hdr",
        "bytes": 41382,
        "width": 512,
        "height": 256
      }
    },
    "gpuBytes": {
      "high": 4194304,
      "medium": 4194304,
      "low": 4194304
    }
  },
  {
    "id": "cinema2-wet-concrete",
    "kind": "texture",
    "layout": "surface-normal-crack-roughness",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/textures/wet-concrete-1024.webp",
        "bytes": 1092670,
        "width": 1024,
        "height": 1024
      },
      "low": {
        "url": "/cinema2/textures/wet-concrete-512.webp",
        "bytes": 442910,
        "width": 512,
        "height": 512
      }
    },
    "gpuBytes": {
      "high": 5592405,
      "medium": 5592405,
      "low": 1398101
    }
  }
] as const satisfies readonly Cinema2GeneratedAssetRecord[]

export type Cinema2AssetId = (typeof CINEMA2_ASSET_RECORDS)[number]['id']
