// GENERATED by `npm run assets:build` from assets/cinema2/*/asset.json. Do not edit by hand.
import type { Cinema2GeneratedAssetRecord } from './Cinema2GeneratedAssetTypes'

export const CINEMA2_ASSET_RECORDS = [
  {
    "id": "cinema2-conduit-chamber",
    "kind": "model",
    "compression": "none",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/models/conduit-chamber.glb",
        "bytes": 4896752,
        "triangles": 105556
      }
    },
    "gpuBytes": {
      "high": 4892096,
      "medium": 4892096,
      "low": 4892096
    }
  },
  {
    "id": "cinema2-conduit-tubes",
    "kind": "model",
    "compression": "none",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/models/conduit-tubes.glb",
        "bytes": 1130416,
        "triangles": 31200
      }
    },
    "gpuBytes": {
      "high": 1109728,
      "medium": 1109728,
      "low": 1109728
    }
  },
  {
    "id": "cinema2-conduit-wordmark",
    "kind": "model",
    "compression": "none",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/models/conduit-wordmark.glb",
        "bytes": 3396360,
        "triangles": 59122
      }
    },
    "gpuBytes": {
      "high": 3391660,
      "medium": 3391660,
      "low": 3391660
    }
  },
  {
    "id": "cinema2-dvydrm-logo",
    "kind": "model",
    "compression": "none",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/models/dvydrm-logo.glb",
        "bytes": 1136736,
        "triangles": 31216
      }
    },
    "gpuBytes": {
      "high": 1134744,
      "medium": 1134744,
      "low": 1134744
    }
  },
  {
    "id": "cinema2-dvydrm-logo-faceted",
    "kind": "model",
    "compression": "none",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/models/dvydrm-logo-faceted.glb",
        "bytes": 520764,
        "triangles": 12732
      }
    },
    "gpuBytes": {
      "high": 518780,
      "medium": 518780,
      "low": 518780
    }
  },
  {
    "id": "cinema2-golden-roots",
    "kind": "model",
    "compression": "none",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/models/golden-roots.glb",
        "bytes": 1900944,
        "triangles": 62812
      }
    },
    "gpuBytes": {
      "high": 1820096,
      "medium": 1820096,
      "low": 1820096
    }
  },
  {
    "id": "cinema2-reference-torus-knot",
    "kind": "model",
    "compression": "meshopt",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/models/reference-torus-knot.glb",
        "bytes": 158960,
        "triangles": 24000
      }
    },
    "gpuBytes": {
      "high": 341456,
      "medium": 341456,
      "low": 341456
    }
  },
  {
    "id": "cinema2-reliquary-trees",
    "kind": "model",
    "compression": "none",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/models/reliquary-trees.glb",
        "bytes": 5904756,
        "triangles": 126952
      }
    },
    "gpuBytes": {
      "high": 5901152,
      "medium": 5901152,
      "low": 5901152
    }
  },
  {
    "id": "cinema2-smoke-sprites",
    "kind": "texture",
    "layout": "sprite-sheet-rgba",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/textures/smoke-sprites-512.webp",
        "bytes": 121430,
        "width": 512,
        "height": 512
      },
      "low": {
        "url": "/cinema2/textures/smoke-sprites-256.webp",
        "bytes": 40712,
        "width": 256,
        "height": 256
      }
    },
    "gpuBytes": {
      "high": 1398101,
      "medium": 1398101,
      "low": 349525
    }
  },
  {
    "id": "cinema2-smoke-volume",
    "kind": "texture",
    "layout": "noise-volume-rgba",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/textures/smoke-volume-64.webp",
        "bytes": 660238,
        "width": 64,
        "height": 64,
        "depth": 64
      },
      "low": {
        "url": "/cinema2/textures/smoke-volume-32.webp",
        "bytes": 103852,
        "width": 32,
        "height": 32,
        "depth": 32
      }
    },
    "gpuBytes": {
      "high": 1398101,
      "medium": 1398101,
      "low": 174763
    }
  },
  {
    "id": "cinema2-studio-environment",
    "kind": "environment",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/environments/studio-1024.hdr",
        "bytes": 152066,
        "width": 1024,
        "height": 512
      },
      "low": {
        "url": "/cinema2/environments/studio-512.hdr",
        "bytes": 42279,
        "width": 512,
        "height": 256
      }
    },
    "gpuBytes": {
      "high": 4194304,
      "medium": 4194304,
      "low": 4194304
    }
  },
  {
    "id": "cinema2-studio-environment-neutral",
    "kind": "environment",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/environments/studio-neutral-1024.hdr",
        "bytes": 148259,
        "width": 1024,
        "height": 512
      },
      "low": {
        "url": "/cinema2/environments/studio-neutral-512.hdr",
        "bytes": 41382,
        "width": 512,
        "height": 256
      }
    },
    "gpuBytes": {
      "high": 4194304,
      "medium": 4194304,
      "low": 4194304
    }
  },
  {
    "id": "cinema2-wet-concrete",
    "kind": "texture",
    "layout": "surface-normal-crack-roughness",
    "license": "generated-in-house",
    "attribution": null,
    "files": {
      "high": {
        "url": "/cinema2/textures/wet-concrete-1024.webp",
        "bytes": 1092670,
        "width": 1024,
        "height": 1024
      },
      "low": {
        "url": "/cinema2/textures/wet-concrete-512.webp",
        "bytes": 442910,
        "width": 512,
        "height": 512
      }
    },
    "gpuBytes": {
      "high": 5592405,
      "medium": 5592405,
      "low": 1398101
    }
  }
] as const satisfies readonly Cinema2GeneratedAssetRecord[]

export type Cinema2AssetId = (typeof CINEMA2_ASSET_RECORDS)[number]['id']
