import type { MusicIntelligenceFrame } from './types'

export const DEFAULT_MI_FRAME: MusicIntelligenceFrame = {
  timeSec:    0,
  frameId:    0,
  sampleRate: 44100,
  sourceId:   null,
  trackId:    null,
  bands: {
    sub:    0,
    bass:   0,
    lowMid: 0,
    mid:    0,
    high:   0,
    air:    0,
    volume: 0,
    normalizedSub:    0,
    normalizedBass:   0,
    normalizedLowMid: 0,
    normalizedMid:    0,
    normalizedHigh:   0,
    normalizedAir:    0,
  },
  rhythm: {
    bpm:              120,
    bpmConfidence:    0,
    beatPhase:        0,
    beatHit:          false,
    beatIndex:        0,
    beatInBar:        0,
    barIndex:         0,
    downbeatHit:      false,
    phrase4Progress:  0,
    phrase8Progress:  0,
    phrase16Progress: 0,
    phrase32Progress: 0,
    phrase4Hit:       false,
    phrase8Hit:       false,
    phrase16Hit:      false,
    phrase32Hit:      false,
    kickHit:          false,
    kickStrength:     0,
    snareHit:         false,
    snareStrength:    0,
    hatHit:           false,
    hatStrength:      0,
    transient:        0,
    transientConfidence: 0,
  },
  energy: {
    instant:      0,
    shortTerm:    0,
    longTerm:     0,
    peak:         0,
    rms:          0,
    crestFactor:  1,
    spectralFlux: 0,
    delta:        0,
    percentile:   0,
    buildProgress: 0,
    dropImpact:   0,
    tension:      0,
    complexity:   0,
    spectralCentroid:  0,
    spectralSpread:    0,
    spectralRolloff:   0,
    spectralFlatness:  0,
  },
  section: {
    type:       null,
    label:      '',
    startSec:   0,
    endSec:     0,
    progress:   0,
    intensity:  0.5,
    confidence: 0,
    source:     'inferred',
  },
  harmonic: {
    key:             null,
    mode:            null,
    keyConfidence:   0,
    chord:           null,
    chordConfidence: 0,
    chordChanged:    false,
    rootNote:        null,
    pitchHz:         null,
    note:            null,
    melodyContour:   null,
  },
  stems: {
    vocals:           0,
    drums:            0,
    bass:             0,
    instruments:      0,
    other:            0,
    vocalEnergy:      0,
    drumEnergy:       0,
    bassStemEnergy:   0,
    instrumentEnergy: 0,
    otherStemEnergy:  0,
    vocalActivity:    0,
    drumTransient:    false,
    bassStemTransient: false,
  },
  lyrics: {
    activeLine:        null,
    activeWord:        null,
    vocalActivity:     0,
    phraseConfidence:  0,
    lyricLineProgress: 0,
    wordHit:           false,
  },
  semantics: {
    buildConfidence:     0,
    dropConfidence:      0,
    fakeoutConfidence:   0,
    vocalHookConfidence: 0,
    mood:    null,
    texture: null,
  },
  raw: {
    freqData:       null,
    timeDomainData: null,
  },
  confidence: {
    overall:  0,
    rhythm:   0,
    harmonic: 0,
    section:  0,
  },
}
