export const MAX_PIX_GRID_LAYERS = 24
export const MAX_PIX_GRID_VISIBLE_LAYERS = 24
export const MAX_PIX_GRID_ANIMATIONS_PER_LAYER = 4

export const MAX_PIX_GRID_SCENES = 32
export const MAX_PIX_GRID_PIXEL_OVERRIDES = 50_000
export const MAX_PIX_GRID_HISTORY = 40

export const MAX_PIX_GRID_GROUPS = 64
export const MAX_PIX_GRID_ACTIVE_GROUPS = 16
export const MAX_PIX_GRID_REACTIONS_PER_GROUP = 8
export const MAX_PIX_GRID_ACTIVE_REACTIONS = 48
export const MAX_PIX_GRID_AUDIO_ASSIGNMENTS = 64
export const MAX_PIX_GRID_CELL_RUNS_PER_GROUP = 4096
export const MAX_PIX_GRID_CONNECTED_REGION_CELLS = 65_536

export const MAX_PIX_GRID_ACTION_CUE_TRACKS = 512
export const MAX_PIX_GRID_ACTION_CUES_PER_TRACK = 4_096

export const MAX_PIX_GRID_MEDIA_SOURCE_BYTES = 64 * 1024 * 1024
export const MAX_PIX_GRID_SVG_SOURCE_CHARACTERS = 2_000_000
