export const MAX_PIX_GRID_LAYERS = 12
export const MAX_PIX_GRID_VISIBLE_LAYERS = 10
export const MAX_PIX_GRID_ANIMATIONS_PER_LAYER = 4

export const MAX_PIX_GRID_SCENES = 32
export const MAX_PIX_GRID_PIXEL_OVERRIDES = 50_000
export const MAX_PIX_GRID_HISTORY = 40
