/**
 * LaserDMX compatibility facade for the engine-neutral Performance Core.
 *
 * New engines should import from `features/performanceCore`. These aliases keep
 * existing Show Director presets, tests, and persisted workflows source-compatible
 * while the implementation lives in the shared layer.
 */
export type {
  BuildSharedPerformanceContextInput as BuildLaserDmxShowDirectorPerformanceContextInput,
  SharedPerformanceBoundaryClassification as LaserDmxShowDirectorPerformanceBoundaryClassification,
  SharedPerformanceBoundaryInfo as LaserDmxShowDirectorPerformanceBoundaryInfo,
  SharedPerformanceContext as LaserDmxShowDirectorPerformanceTimingContext,
  SharedPerformanceGridPosition as LaserDmxShowDirectorPerformanceGridPosition,
  SharedPerformanceMacroSection as LaserDmxShowDirectorPerformanceMacroSection,
  SharedPerformanceMusicIntelligenceAdapter as LaserDmxShowDirectorPerformanceMusicIntelligenceAdapter,
  SharedPerformanceResolvedSection as LaserDmxShowDirectorPerformanceResolvedSection,
} from '../../../features/performanceCore/context'

export {
  buildSharedPerformanceContext as buildLaserDmxShowDirectorPerformanceContext,
  buildSharedPerformanceContextFromAudioFeatureBus as buildLaserDmxShowDirectorPerformanceContextFromAudioFeatureBus,
  classifySharedPerformanceBoundary as classifyLaserDmxShowDirectorPerformanceBoundary,
  createSharedPerformanceAnalysisIdentity as createLaserDmxShowDirectorAnalysisIdentity,
  createSharedPerformanceMusicIntelligenceAdapter as createLaserDmxShowDirectorMusicIntelligenceAdapter,
  createSharedPerformanceSectionIdentity as createLaserDmxShowDirectorSectionIdentity,
  didCrossSharedPerformanceBarBoundary as didCrossLaserDmxShowDirectorBarBoundary,
  didCrossSharedPerformanceBeatBoundary as didCrossLaserDmxShowDirectorBeatBoundary,
  didCrossSharedPerformanceEightBarBoundary as didCrossLaserDmxShowDirectorEightBarBoundary,
  didCrossSharedPerformanceEveryNBarsBoundary as didCrossLaserDmxShowDirectorEveryNBarsBoundary,
  didCrossSharedPerformanceFourBarBoundary as didCrossLaserDmxShowDirectorFourBarBoundary,
  didCrossSharedPerformanceSixteenBarBoundary as didCrossLaserDmxShowDirectorSixteenBarBoundary,
  didEnterSharedPerformanceSection as didEnterLaserDmxShowDirectorSection,
  didExitSharedPerformanceSection as didExitLaserDmxShowDirectorSection,
  resolveSharedPerformanceDropOccurrence as resolveLaserDmxShowDirectorDropOccurrence,
  resolveSharedPerformanceGridPosition as resolveLaserDmxShowDirectorGridPosition,
  resolveSharedPerformanceMacroSectionAtTime as resolveLaserDmxShowDirectorMacroSectionAtTime,
  resolveSharedPerformanceMacroSectionOccurrence as resolveLaserDmxShowDirectorMacroSectionOccurrence,
  resolveSharedPerformanceMacroSections as resolveLaserDmxShowDirectorMacroSections,
  resolveSharedPerformanceSectionAtTime as resolveLaserDmxShowDirectorSectionAtTime,
  resolveSharedPerformanceSectionOccurrence as resolveLaserDmxShowDirectorSectionOccurrence,
  resolveSharedPerformanceSections as resolveLaserDmxShowDirectorPerformanceSections,
} from '../../../features/performanceCore/context'
